// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.nexora.nexora.notifications

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object NotificationApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * The notification classes FR-NOTIFY-001 names, one Android notification
 * channel per category (created once at attach, `NotificationChannels.kt`).
 * `backgroundService` is a tenth category for `E10-T08`'s mandatory ongoing
 * foreground-service notification — declared here so T08 adds no channel
 * plumbing of its own. This task does not decide *when* any category is
 * used (E10-T01 §4) — that is T03-T08.
 */
enum class NotificationCategory(val raw: Int) {
  MESSAGE(0),
  VOICE_MESSAGE(1),
  PTT(2),
  INCOMING_CALL(3),
  CONNECTION_REQUEST(4),
  TRUST_REQUEST(5),
  GROUP_EVENT(6),
  SECURITY_EVENT(7),
  STORAGE_WARNING(8),
  BACKGROUND_SERVICE(9);

  companion object {
    fun ofRaw(raw: Int): NotificationCategory? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * A single notification post/replace request. [id] is stable per logical
 * notification — re-posting the same [id] replaces the prior post (Android
 * `NotificationManagerCompat.notify(id, ...)` semantics), it is not an
 * auto-incrementing counter.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NotificationRequest (
  val id: Long,
  val category: NotificationCategory,
  val title: String,
  val body: String,
  /**
   * True only for `backgroundService` — an ongoing notification the user
   * cannot swipe away, per Android's foreground-service contract (E10-T08).
   */
  val ongoing: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NotificationRequest {
      val id = pigeonVar_list[0] as Long
      val category = pigeonVar_list[1] as NotificationCategory
      val title = pigeonVar_list[2] as String
      val body = pigeonVar_list[3] as String
      val ongoing = pigeonVar_list[4] as Boolean
      return NotificationRequest(id, category, title, body, ongoing)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      category,
      title,
      body,
      ongoing,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NotificationRequest
    return NotificationApiPigeonUtils.deepEquals(this.id, other.id) && NotificationApiPigeonUtils.deepEquals(this.category, other.category) && NotificationApiPigeonUtils.deepEquals(this.title, other.title) && NotificationApiPigeonUtils.deepEquals(this.body, other.body) && NotificationApiPigeonUtils.deepEquals(this.ongoing, other.ongoing)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NotificationApiPigeonUtils.deepHash(this.id)
    result = 31 * result + NotificationApiPigeonUtils.deepHash(this.category)
    result = 31 * result + NotificationApiPigeonUtils.deepHash(this.title)
    result = 31 * result + NotificationApiPigeonUtils.deepHash(this.body)
    result = 31 * result + NotificationApiPigeonUtils.deepHash(this.ongoing)
    return result
  }
  override fun toString(): String {
    return "NotificationRequest(id=$id, category=$category, title=$title, body=$body, ongoing=$ongoing)"
  }
}
private open class NotificationApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NotificationCategory.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NotificationRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NotificationCategory -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is NotificationRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Host-side API: Dart calls into native Kotlin.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface NotificationApi {
  /**
   * Idempotent: creates one `NotificationChannel` per [NotificationCategory]
   * if it does not already exist. Safe to call on every attach.
   */
  fun ensureChannels()
  /**
   * True when notifications may be posted right now. On API < 33 (no
   * runtime permission exists) this is always true; on API 33+ it reflects
   * whether `POST_NOTIFICATIONS` has been granted.
   */
  fun hasPermission(): Boolean
  /**
   * Triggers the system permission prompt on API 33+. No-op on API < 33.
   * The result reaches Dart via `NotificationEventsApi.onPermissionResult`.
   */
  fun requestPermission()
  /**
   * Posts (or replaces, by [NotificationRequest.id]) a notification.
   * Returns false — and does not throw — when the host refused to post
   * (no permission, or the user disabled notifications for the app/channel).
   */
  fun post(request: NotificationRequest): Boolean
  /**
   * Withdraws a previously posted notification by id. No-op if [id] was
   * never posted or was already withdrawn.
   */
  fun cancel(id: Long)

  companion object {
    /** The codec used by NotificationApi. */
    val codec: MessageCodec<Any?> by lazy {
      NotificationApiPigeonCodec()
    }
    /** Sets up an instance of `NotificationApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NotificationApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nexora.NotificationApi.ensureChannels$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.ensureChannels()
              listOf(null)
            } catch (exception: Throwable) {
              NotificationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nexora.NotificationApi.hasPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.hasPermission())
            } catch (exception: Throwable) {
              NotificationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nexora.NotificationApi.requestPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestPermission()
              listOf(null)
            } catch (exception: Throwable) {
              NotificationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nexora.NotificationApi.post$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as NotificationRequest
            val wrapped: List<Any?> = try {
              listOf(api.post(requestArg))
            } catch (exception: Throwable) {
              NotificationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nexora.NotificationApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.cancel(idArg)
              listOf(null)
            } catch (exception: Throwable) {
              NotificationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Flutter-side API: native Kotlin calls into Dart.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class NotificationEventsApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by NotificationEventsApi. */
    val codec: MessageCodec<Any?> by lazy {
      NotificationApiPigeonCodec()
    }
  }
  /**
   * Fired once the runtime permission prompt (`requestPermission()`)
   * resolves, forwarded from `MainActivity.onRequestPermissionsResult`.
   */
  suspend fun onPermissionResult(grantedArg: Boolean)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.nexora.NotificationEventsApi.onPermissionResult$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(grantedArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(NotificationApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  /**
   * Fired when the user taps a posted notification. Delivered to Dart and
   * otherwise unconsumed as of E10-T01 (`OQ-E10-T01-1`) — no approved design
   * says where a tap should land.
   */
  suspend fun onNotificationTapped(idArg: Long, categoryArg: NotificationCategory)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.nexora.NotificationEventsApi.onNotificationTapped$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(idArg, categoryArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(NotificationApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
