// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.nexora.nexora.transport

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object TransportApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * The physical/logical carrier a `TransportDevice` was discovered or
 * connected over. Bluetooth is the only carrier a real implementation
 * exists for (T03b/T03c); `wifiDirect`/`internet` are named here because
 * they are part of the shape every future transport must fit (ADR-0004),
 * not because either is implemented.
 */
enum class TransportType(val raw: Int) {
  BLUETOOTH(0),
  WIFI_DIRECT(1),
  INTERNET(2);

  companion object {
    fun ofRaw(raw: Int): TransportType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Lifecycle state of a connection to a given device id. */
enum class ConnectionState(val raw: Int) {
  CONNECTING(0),
  CONNECTED(1),
  DISCONNECTED(2),
  FAILED(3);

  companion object {
    fun ofRaw(raw: Int): ConnectionState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * A device/peer as seen by the native transport layer, before any app-level
 * identity/session concept is layered on top (that's `core/auth`,
 * ADR-0005 — out of scope here).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TransportDevice (
  val id: String,
  val displayName: String,
  val type: TransportType,
  /**
   * Signal strength in dBm, when the native layer can supply it (e.g.
   * Android's Bluetooth scan result RSSI). Null when unavailable.
   *
   * Contract-only as of E04-B03: no native implementation populates this
   * field yet — wiring real RSSI is E05's job (FR-ROUTE-001, FR-ROUTE-002).
   */
  val rssi: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TransportDevice {
      val id = pigeonVar_list[0] as String
      val displayName = pigeonVar_list[1] as String
      val type = pigeonVar_list[2] as TransportType
      val rssi = pigeonVar_list[3] as Long?
      return TransportDevice(id, displayName, type, rssi)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      displayName,
      type,
      rssi,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TransportDevice
    return TransportApiPigeonUtils.deepEquals(this.id, other.id) && TransportApiPigeonUtils.deepEquals(this.displayName, other.displayName) && TransportApiPigeonUtils.deepEquals(this.type, other.type) && TransportApiPigeonUtils.deepEquals(this.rssi, other.rssi)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TransportApiPigeonUtils.deepHash(this.id)
    result = 31 * result + TransportApiPigeonUtils.deepHash(this.displayName)
    result = 31 * result + TransportApiPigeonUtils.deepHash(this.type)
    result = 31 * result + TransportApiPigeonUtils.deepHash(this.rssi)
    return result
  }
  override fun toString(): String {
    return "TransportDevice(id=$id, displayName=$displayName, type=$type, rssi=$rssi)"
  }
}
private open class TransportApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TransportType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ConnectionState.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TransportDevice.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TransportType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ConnectionState -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is TransportDevice -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Host-side API: Dart calls into native Kotlin.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface TransportApi {
  fun startDiscovery()
  fun stopDiscovery()
  fun connect(deviceId: String): Boolean
  fun disconnect(deviceId: String)
  fun send(deviceId: String, bytes: ByteArray): Boolean
  /**
   * Requests this device become discoverable to nearby peers for a fixed,
   * time-boxed window (120s), via Android's own
   * `ACTION_REQUEST_DISCOVERABLE` system dialog (E04-B09,
   * `FR-DISC-001`) — the human-decided discoverability mechanism (not a
   * continuous listen-only scan mode). Fire-and-forget from the Dart side:
   * the OS system dialog handles user confirmation, and there is no
   * return value or settled-state event to await.
   */
  fun requestDiscoverable()

  companion object {
    /** The codec used by TransportApi. */
    val codec: MessageCodec<Any?> by lazy {
      TransportApiPigeonCodec()
    }
    /** Sets up an instance of `TransportApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TransportApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nexora.TransportApi.startDiscovery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startDiscovery()
              listOf(null)
            } catch (exception: Throwable) {
              TransportApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nexora.TransportApi.stopDiscovery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopDiscovery()
              listOf(null)
            } catch (exception: Throwable) {
              TransportApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nexora.TransportApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.connect(deviceIdArg))
            } catch (exception: Throwable) {
              TransportApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nexora.TransportApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.disconnect(deviceIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              TransportApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nexora.TransportApi.send$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val bytesArg = args[1] as ByteArray
            val wrapped: List<Any?> = try {
              listOf(api.send(deviceIdArg, bytesArg))
            } catch (exception: Throwable) {
              TransportApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nexora.TransportApi.requestDiscoverable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestDiscoverable()
              listOf(null)
            } catch (exception: Throwable) {
              TransportApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Flutter-side API: native Kotlin calls into Dart.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class TransportEventsApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by TransportEventsApi. */
    val codec: MessageCodec<Any?> by lazy {
      TransportApiPigeonCodec()
    }
  }
  suspend fun onDeviceDiscovered(deviceArg: TransportDevice)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.nexora.TransportEventsApi.onDeviceDiscovered$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(deviceArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(TransportApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onDeviceLost(deviceIdArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.nexora.TransportEventsApi.onDeviceLost$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(deviceIdArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(TransportApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onConnectionStateChanged(deviceIdArg: String, stateArg: ConnectionState)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.nexora.TransportEventsApi.onConnectionStateChanged$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(deviceIdArg, stateArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(TransportApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onDataReceived(deviceIdArg: String, bytesArg: ByteArray)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.nexora.TransportEventsApi.onDataReceived$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(deviceIdArg, bytesArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(TransportApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  /**
   * Link-quality signal for a given neighbor, when the native layer can
   * measure it (round-trip latency, observed packet loss).
   *
   * Contract-only as of E04-B03: declared here so `RoutingEngine` has a
   * stable production event to consume, but nothing in this repo calls
   * this method yet — no native implementation emits it. Wiring real
   * Bluetooth latency/loss measurements into this event and calling
   * `RoutingEngine.recordLinkMeasurement` from it is E05's job
   * (FR-ROUTE-001, FR-ROUTE-002). Do not synthesize values here.
   */
  suspend fun onLinkQuality(deviceIdArg: String, latencyMsArg: Long, lossRateArg: Double)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.nexora.TransportEventsApi.onLinkQuality$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(deviceIdArg, latencyMsArg, lossRateArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(TransportApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
